package com.mihael.mhipster.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MDLSAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMDLSAllPropertiesEquals(MDLS expected, MDLS actual) {
        assertMDLSAutoGeneratedPropertiesEquals(expected, actual);
        assertMDLSAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMDLSAllUpdatablePropertiesEquals(MDLS expected, MDLS actual) {
        assertMDLSUpdatableFieldsEquals(expected, actual);
        assertMDLSUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMDLSAutoGeneratedPropertiesEquals(MDLS expected, MDLS actual) {
        assertThat(expected)
            .as("Verify MDLS auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMDLSUpdatableFieldsEquals(MDLS expected, MDLS actual) {
        assertThat(expected)
            .as("Verify MDLS relevant properties")
            .satisfies(e -> assertThat(e.getBaseConfig()).as("check baseConfig").isEqualTo(actual.getBaseConfig()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMDLSUpdatableRelationshipsEquals(MDLS expected, MDLS actual) {
        // empty method
    }
}
